name: Native Build

on:
    workflow_dispatch:
    workflow_call:
    push:

jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-20.04 ]
            fail-fast: false
        env:
            HYDRA_NATIVE_BUILD: true
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'
            -   name: Install all with Maven
                run: mvn --batch-mode install -DskipTests -T 1C
            -   name: NativeImage
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '17'
                    version: 'latest'
                    components: 'native-image'
                    cache: 'maven'
                    #                    native-image-musl: true
                    github-token: ${{ secrets.GITHUB_TOKEN }}
            -   name: Build
                working-directory: ./core
                run: |
                    mvn --batch-mode -P native native:compile -DskipTests
            -   name: Upload linux artifact
                uses: actions/upload-artifact@v3
                if: runner.os == 'Linux'
                with:
                    name: coreLinux
                    path: core/target/core
            #            -   name: Upload windows artifact
            #                uses: actions/upload-artifact@v3
            #                if: runner.os == 'Windows'
            #                with:
#                    name: coreWindows
#                    path: |
#                        core\target\core.exe
#                        core\target\*.dll
