name: Native Build

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-20.04 ]
            fail-fast: false
        env:
            HYDRA_NATIVE_BUILD: true
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
                with:
                    # Check out last 15 commits
                    fetch-depth: 15

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'

            -   name: "Get changed files in core module"
                id: changed-files-specific
                uses: tj-actions/changed-files@v35
                with:
                    since_last_remote_commit: true
                    files: |
                        core/**

            -   if: steps.changed-files-specific.outputs.any_changed == 'true'
                run: |
                    echo "::notice::Will build new native image / docker container. Changed files in core since last push:"
                    echo "${{ steps.changed-files-specific.outputs.all_changed_files }}"

            -   if: steps.changed-files-specific.outputs.any_changed == 'false'
                run: |
                    echo "::notice::Will skip build of native image / docker container. No changed files in core since last push."

            -   name: NativeImage
                uses: graalvm/setup-graalvm@v1
                if: steps.changed-files-specific.outputs.any_changed == 'true'
                with:
                    java-version: '17'
                    version: 'latest'
                    components: 'native-image'
                    cache: 'maven'
                    github-token: ${{ secrets.GITHUB_TOKEN }}

            -   name: "Install all with Maven"

                run: mvn --batch-mode clean install -DskipTests -T 1C
            -   name: "Run unit tests"
                run: mvn --batch-mode test -T 1C -pl !org.nzbhydra:tests,!org.nzbhydra.tests:system --fail-at-end

            -   name: "Create test Report"
                uses: dorny/test-reporter@v1
                if: always()
                continue-on-error: true
                with:
                    name: Unit test report
                    path: "**/surefire-reports/*.xml"
                    reporter: java-junit

            -   name: "Build native image"
                if: steps.changed-files-specific.outputs.any_changed == 'true'
                working-directory: ./core
                run: |
                    mvn --batch-mode -Pnative clean native:compile -DskipTests

            -   name: "UPX linux artifact"
                if: steps.changed-files-specific.outputs.any_changed == 'true'
                uses: crazy-max/ghaction-upx@v2
                with:
                    files: core/target/core
                    args: -q

            -   name: "Upload linux artifact"
                if: steps.changed-files-specific.outputs.any_changed == 'true'
                uses: actions/upload-artifact@v3
                with:
                    name: coreLinux
                    path: core/target/core

            -   name: "Copy artifact to include folder"
                if: steps.changed-files-specific.outputs.any_changed == 'true'
                run: |
                    mv core/target/core ./docker/nativeTest/
                    chmod +x ./docker/nativeTest/core

            -   name: "Login to GitHub Container Registry"
                if: steps.changed-files-specific.outputs.any_changed == 'true'
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: "Build core and push container"
                if: steps.changed-files-specific.outputs.any_changed == 'true'
                run: |
                    cp other/wrapper/nzbhydra2wrapperPy3.py ./docker/nativeTest/
                    cd ./docker/nativeTest/
                    docker build -t hydradocker .
                    docker tag hydradocker:latest ghcr.io/theotherp/hydradocker:latest
                    docker push ghcr.io/theotherp/hydradocker:latest
