name: Native Build

on: [ workflow_dispatch, push ]

jobs:
    build:
        env:
            HYDRA_NATIVE_BUILD: true
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'
            -   name: Install all with Maven
                run: mvn --batch-mode install -DskipTests
            -   name: NativeImage
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '17'
                    version: 'latest'
                    components: 'native-image'
                    cache: 'maven'

            -   name: Build
                working-directory: ./core
                run: |
                  java --version
                  gu --version
                  mvn --batch-mode -P native native:compile -DskipTests
            -   uses: actions/upload-artifact@v3
                with:
                    name: core
                    path: /home/runner/work/nzbhydra2/nzbhydra2/core/target/core
