name: Native Build

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-20.04 ]
            fail-fast: false
        env:
            HYDRA_NATIVE_BUILD: true
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'
            -   name: NativeImage
                uses: graalvm/setup-graalvm@v1
                if: "!contains(github.event.head_commit.message, 'skipnativebuild')"
                with:
                    java-version: '17'
                    version: 'latest'
                    components: 'native-image'
                    cache: 'maven'
                    github-token: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Install all with Maven"
                run: mvn --batch-mode clean install -DskipTests -T 1C
            -   name: "Run unit tests"
                run: mvn --batch-mode test -T 1C -pl !org.nzbhydra:tests,!org.nzbhydra.tests:system --fail-at-end
            -   name: "Create test Report"
                uses: dorny/test-reporter@v1
                if: always()
                continue-on-error: true
                with:
                    name: Unit test report
                    path: "**/surefire-reports/*.xml"
                    reporter: java-junit
            -   name: "Build native image"
                if: "!contains(github.event.head_commit.message, 'skipnativebuild')"
                working-directory: ./core
                run: |
                    mvn --batch-mode -Pnative clean native:compile -DskipTests
            -   name: "Upload linux artifact"
                if: "!contains(github.event.head_commit.message, 'skipnativebuild')"
                uses: actions/upload-artifact@v3
                with:
                    name: coreLinux
                    path: core/target/core
            -   name: "Copy artifact to include folder"
                if: "!contains(github.event.head_commit.message, 'skipnativebuild')"
                run: |
                    mv core/target/core ./docker/nativeTest/
                    chmod +x ./docker/nativeTest/core
            -   name: "Login to GitHub Container Registry"
                if: "!contains(github.event.head_commit.message, 'skipnativebuild')"
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Build core and push container"
                if: "!contains(github.event.head_commit.message, 'skipnativebuild')"
                run: |
                    cp other/wrapper/nzbhydra2wrapperPy3.py ./docker/nativeTest/
                    cd ./docker/nativeTest/
                    docker build -t hydradocker .
                    docker tag hydradocker:latest ghcr.io/theotherp/hydradocker:latest
                    docker push ghcr.io/theotherp/hydradocker:latest
