name: system-test

on:
    push:
    workflow_dispatch:

jobs:
    waitForNative:
        uses: ./.github/workflows/buildNative.yml
    prepareArtifacts:
        # If we skipped the build of the native image we need to download the last uploaded one (from a previous run)
        # and upload it again to make it available to the next jobs
        needs: [ waitForNative ]
        if: "contains(github.event.head_commit.message, 'skipnativebuild')"
        runs-on: ubuntu-latest
        steps:
            -   run: true
            -   name: "Download artifact from previous build"
                if: "contains(github.event.head_commit.message, 'skipnativebuild')"
                uses: dawidd6/action-download-artifact@v2
                with:
                    workflow: buildNative.yml
                    name: coreLinux
            -   name: "Upload linux artifact"
                if: "contains(github.event.head_commit.message, 'skipnativebuild')"
                uses: actions/upload-artifact@v3
                with:
                    name: coreLinux
                    path: core
    prepareContainer:
        needs: [ prepareArtifacts ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                name: "Check out source"
            -   name: "Display structure of working directory"
                run: ls .
            -   uses: actions/download-artifact@v3
                name: "Download native artifacts"
                with:
                    path: ~/artifacts
                    name: coreLinux
            -   name: "Display structure of artifacts folder"
                run: ls -laR ~/artifacts
            -   name: "Display structure of current folder"
                run: ls -la .
            -   name: "Copy artifacts to include folders"
                run: |
                    mv ~/artifacts/core ./docker/nativeTest/
                    chmod +x ./docker/nativeTest/core
            -   name: "Login to GitHub Container Registry"
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Build core container"
                run: |
                    cp other/wrapper/nzbhydra2wrapperPy3.py ./docker/nativeTest/
                    cd ./docker/nativeTest/
                    docker build -t hydradocker .
                    docker tag hydradocker:latest ghcr.io/theotherp/hydradocker:latest
                    docker push ghcr.io/theotherp/hydradocker:latest
    buildMockserver:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                name: "Check out source"
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'
            -   name: "Login to GitHub Container Registry"
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: "Upload settings.xml"
                uses: actions/upload-artifact@v3
                with:
                    name: settings
                    path: $HOME/.m2/settings.xml
            -   name: "Build and push mockserver container"
                run: |
                    mvn --batch-mode install -DskipTests -T 1C
                    cd other/mockserver/
                    mvn --batch-mode spring-boot:build-image
                    docker tag mockserver:3.0.0 ghcr.io/theotherp/mockserver:3.0.0
                    docker push ghcr.io/theotherp/mockserver:3.0.0

    runSystemTests:
        needs: [ prepareContainer, buildMockserver ]
        runs-on: ubuntu-latest
        env:
            spring_profiles_active: build,systemtest
        services:
            core:
                image: ghcr.io/theotherp/hydradocker:latest
                ports:
                    - 5076:5076
                credentials:
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                volumes:
                    - /tmp/data:/data
                env:
                    spring_profiles_active: build,systemtest
            mockServer:
                image: ghcr.io/theotherp/mockserver:3.0.0
                ports:
                    - 5080:5080
                credentials:
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                env:
                    spring_profiles_active: build,systemtest
            sonarr:
                image: lscr.io/linuxserver/sonarr:latest
                ports:
                    - 8989:8989
                credentials:
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                volumes:
                    - ./docker/sonarr/data/:/config
            radarr:
                image: lscr.io/linuxserver/radarr:latest
                ports:
                    - 8989:8989
                credentials:
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                volumes:
                    - ./docker/radarr/data/:/config
        steps:
            -   uses: actions/checkout@v3
                name: "Check out source"

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'
            -   name: "Install"
                run: mvn --batch-mode clean install -pl org.nzbhydra:shared,org.nzbhydra:mapping,org.nzbhydra:config
            -   name: "Run tests"
                run: mvn --batch-mode test -pl org.nzbhydra.tests:system
            -   name: "Upload data folder artifact"
                uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: data
                    path: /tmp/data
            -   name: "Create test Report"
                uses: dorny/test-reporter@v1
                if: always()
                continue-on-error: true
                with:
                    name: System test report
                    path: "**/surefire-reports/*.xml"
                    reporter: java-junit
