name: system-test

on:
    push:
    workflow_dispatch:

jobs:
    waitForNative:
        uses: ./.github/workflows/buildNative.yml
    buildMockserver:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                name: "Check out source"
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'

            -   name: "Login to GitHub Container Registry"
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: "Build and push mockserver container"
                run: |
                    mvn --batch-mode install -DskipTests -T 1C
                    cd other/mockserver/
                    mvn --batch-mode spring-boot:build-image
                    docker tag mockserver:3.0.0 ghcr.io/theotherp/mockserver:3.0.0
                    docker push ghcr.io/theotherp/mockserver:3.0.0

    runSystemTests:
        needs: [ waitForNative, buildMockserver ]
        runs-on: ubuntu-latest
        env:
            spring_profiles_active: build,systemtest
        steps:
            -   uses: actions/checkout@v3
                name: "Check out source"

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
                    cache: 'maven'

            -   name: "Install"
                run: mvn --batch-mode clean install -DskipTests -pl org.nzbhydra:shared,org.nzbhydra:mapping

            -   name: "Create docker network"
                run: docker network create systemtest

            -   name: "Copy v1Migration docker data"
                run: |
                    mkdir -p /tmp/hydra/v1MigrationDataFolder
                    cp -R tests/system/instanceData/v1Migration/* /tmp/hydra/v1MigrationDataFolder/

            -   name: "Run docker compose"
                run: |
                    cd docker
                    docker-compose up -d

            -   name: "Wait for healthy containers"
                run: |
                    docker ps
                    sleep 10
                    docker ps
                    sleep 10
                    docker ps

            -   name: "Run tests"
                run: mvn --batch-mode test -pl org.nzbhydra.tests:system -DtrimStackTrace=false

            -   name: "Upload data folder artifact"
                uses: actions/upload-artifact@v3
                if: always()
                with:
                    name: data
                    path: /tmp/hydra

            -   name: "Create test Report"
                uses: dorny/test-reporter@v1
                if: always()
                continue-on-error: true
                with:
                    name: System test report
                    path: "**/surefire-reports/*.xml"
                    reporter: java-junit
